### ISSUE TITLE
Need support for HTTP/S proxies

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#76] opened 2017-08-08 14:42 UTC
Running the Validator within a corporate intranet can require the use of an HTTP proxy.  The requests library has this support, the parameters just need to be added to the config.ini files and passed into the library.

**Comment by tomasg2012** [comment] 2017-08-10 22:03
Still needs to be tested, but the code is available in latest PR.

**Comment by mraineri** [comment] 2017-12-14 22:21
Assigning to @jautor to test

**Comment by jautor** [comment] 2018-01-31 22:14
I've run into issues today with it, and here's the exception code.  I'm not certain the proxy input/formats are correct (could be my issue), however I do see a likely issue - the proxy settings should only be used / applied when connecting to the Internet (meaning, the DMTF schema repo or other sites), and not when connecting to the system under test.  That will certainly fail, and it appears to be the case here.  We may need a separate setting for "target proxy settings", but I would expect that to be an edge case (although a Plugfest over the Internet would hit it!).

~~~
Something went wrong
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 589, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 797, in _prepare_proxy
    conn.connect()
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connection.py",
line 267, in connect
    self._tunnel()
  File "C:\Python35\lib\http\client.py", line 919, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 503 Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\util\retry.py",
line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<< IP Address of target system under test>>, port=443): Max retries exceeded with url: /redfish/v1/ (Caused by
 ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 S
ervice Unavailable',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1268, in main
    rst.setConfig({key: cdict[key] for key in cdict.keys() if key in rst.configs
et.keys()})
  File "C:\Users\JAUTOR\Documents\GitHub\Redfish-Service-Validator\traverseServi
ce.py", line 103, in setConfig
    success = currentSession.startSession(User, Passwd, config['configuri'], cer
tVal, proxies)
  File "C:\Users\JAUTOR\Documents\GitHub\Redfish-Service-Validator\rfSession.py"
, line 45, in startSession
    sr = requests.get(server + '/redfish/v1/', verify=chkCert, headers=commonHea
der, proxies=proxies)
  File "C:\Python35\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python35\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='<<IP address of target system>>', port=
443): Max retries exceeded with url: /redfish/v1/ (Caused by ProxyError('Cannot
connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',
)))
~~~

**Comment by billdodd** [comment] 2018-02-01 19:52
Jeff, you are right about the cause of the failure. The proxy settings are being used for all connections (system under test as well as any external URLs). Changing it to only apply to external URLs is easy. But will that be the expected behavior in all environments (or at least cover the 80% in the 80/20 rule)?

**Comment by billdodd** [comment] 2018-02-02 17:47
Per discussion in the Tools TF call, will change the behavior to limit proxy use to external requests (no proxy use for the system under test).

**Closed** 2018-02-08 22:32 UTC
Labels: enhancement
