### ISSUE TITLE
Use of Self-Signed Server Certificate may require new cert file import in config

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#69] opened 2017-08-04 14:52 UTC
It is common for servers in data center to use locally-generated self-signed certificate as a cost-saving.  In a test I created appropriate certificate, installed into BMC and also the certificate store in the Windows client machine, and both Internet Explorer and Chrome are no longer showing certificate errors when Redfish service is accessed.

But it appears that Python requests lib does not use the system certificate store to identify authorized CA.
http://docs.python-requests.org/en/latest/user/advanced/ 
Instead it seems we need to add verify parameter 

`You can pass verify the path to a CA_BUNDLE file or directory with certificates of trusted CAs:
>>> requests.get('https://github.com', verify='/path/to/certfile')
or persistent:
s = requests.Session()
s.verify = '/path/to/certfile'`
 
Does the team think it valuable to add new parameter to the config file to specify the cert file?
Used with exiting config option `CertificateCheck = On`
Would remove all the annoying cert warnings from stdout...

Or perhaps there is another way.

**Comment by billdodd** [comment] 2017-08-04 17:47
Makes sense to me. We're already using the `verify` parameter with requests in the case of disabling cert path validation (`verify=False`). Adding an option to specify trusted signing certs would be useful for the scenario described and straightforward to implement.

**Comment by jbobzin-insyde** [comment] 2017-08-05 15:20
May I suggest using the s.verify form at entry and putting in a try block?
Apparently the path can be a directory but I really do not understand that form.
A single PEM file is good for me.

If you place a patch in a branch I can test easily.

**Comment by tomasg2012** [comment] 2017-08-08 12:45
I'm not totally familiar with certificates, but it should be easy to put a passthrough to the requests made in the program.  That being said, I thought certificates were pulled from the OS in some fashion, I'm not totally familiar with the world of certificate checking.  I can get a patch in soon.

**Comment by jbobzin-insyde** [comment] 2017-08-08 12:50
Agree quite straightforward. Add new option to pass the certificate file to to s.verify.
`s = requests.Session()
 s.verify = '/path/to/certfile'`

I too was surprised when I discovered that Internet Browsers use a common system certificate store but Python requests does not. 

Not a high priority. But I wanted to test without the warnings.

**Comment by tomasg2012** [comment] 2017-08-10 22:05
Still needs to be tested, but the code is available in latest PR.

**Comment by jbobzin-insyde** [comment] 2017-08-15 19:40
Attempted test today but SSL does not like my cert file. I have some ideas to follow. Stand by.

**Comment by tomasg2012** [comment] 2017-08-24 17:43
Would like to know if anything had changed in this development, I might've missed a memo last week.

**Comment by jbobzin-insyde** [comment] 2017-08-24 18:48
No, I have not spent more time with tests.

**Comment by mraineri** [comment] 2017-12-14 22:23
Assigning to @tomasg2012 to test; if his testing is good, we'll close the issue.

@jbobzin-insyde if you're still seeing issues on your side, please reopen.

**Comment by mraineri** [comment] 2017-12-14 22:38
May need to do more investigation on this...

Would like to avoid using the "no check" option, since even with that it still prints out a lot of warnings; any way to suppress this?

**Comment by mraineri** [comment] 2017-12-14 22:39
@tomasg2012 will post steps to get this to work successfully

**Comment by billdodd** [comment] 2017-12-15 21:33
I tested the service validator against a service that uses a self-signed cert and confirmed that the `--ca_bundle` option added previously does work as expected. (Though I did have to make one small fix that impacted Session logins. That fix will be in a PR to be submitted shortly...)

First, here is the result when specifying `--nochkcert` (works as expected since cert checking is disabled):

```
$ python3 RedfishServiceValidator.py -i idrac --authtype Basic -u <user> -p <password> --nochkcert --payload Single /redfish/v1/Systems

ConfigURI: https://idrac
System Info: No desc
authtype: Basic,  certificatebundle: None,  certificatecheck: False,  config: None,  httpproxy: None,  httpsproxy: None,  
linklimit: {},  localonlymode: False,  logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  payloadfilepath: /redfish/v1/Systems,  payloadmode: Single,  
sample: 0,  schemasuffix: _v1.xml,  servicemode: False,  timeout: 30,  token: None,  username: root,  
usessl: True,  v: False,  
Start time: 12/15/17 - 14:45:21

*** Target, /redfish/v1/Systems
Annotations generated: 0 out of 0
#ComputerSystemCollection.ComputerSystemCollection:Members
	value: [OrderedDict([('@odata.id', '/redfish/v1/Systems/System.Embedded.1')])] <class 'list'>
	has Type: Collection(ComputerSystem.ComputerSystem) entity
	is Optional
	is Collection
	Success
Resource.v1_0_0.ResourceCollection:Description
	value: Collection of Computer Systems <class 'str'>
	has Type: Resource.Description Edm.String
	is Optional
	Success
Resource.v1_0_0.ResourceCollection:Name
	value: Computer System Collection <class 'str'>
	has Type: Resource.Name Edm.String
	is Optional
	Success
Resource.v1_0_0.ResourceCollection:Oem
	value: n/a <class 'str'>
	has Type: Resource.Oem complex
	Oem is skipped
In the resource $metadata, the RedfishExtensions.v1_0_0 namespace must have an alias of 'Redfish'. The alias is missing. This may cause properties of the form [PropertyName]@Redfish.TermName to be unrecognized.
Target, ComputerSystemCollection, ComputerSystemCollection
@odata.context                                          PASS
@odata.id                                               PASS
@odata.type                                             PASS
Description                                             PASS
Members                                                  ...
Members@odata.count                                     PASS
Name                                                    PASS
Members#0                                               PASS
Oem                                                  skipOEM
#ComputerSystemCollection.ComputerSystemCollection, Counter({'pass': 3, 'passGet': 1, 'skipOem': 1})
Elapsed time: 0:00:21
1
Counter({'pass': 3, 'passGet': 1, 'skipOem': 1})
Validation has succeeded.
```

And now the results without the `--nochkcert` option (fails as expected with an `SSLError` because the server cert is not trusted):

```
$ python3 RedfishServiceValidator.py -i idrac --authtype Basic -u <user> -p <password> --payload Single /redfish/v1/Systems

ConfigURI: https://idrac
System Info: No desc
authtype: Basic,  certificatebundle: None,  certificatecheck: True,  config: None,  httpproxy: None,  httpsproxy: None,  
linklimit: {},  localonlymode: False,  logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  payloadfilepath: /redfish/v1/Systems,  payloadmode: Single,  
sample: 0,  schemasuffix: _v1.xml,  servicemode: False,  timeout: 30,  token: None,  username: root,  
usessl: True,  v: False,  
Start time: 12/15/17 - 14:49:10

*** Target, /redfish/v1/Systems
SSLError on /redfish/v1/Systems
/redfish/v1/Systems:  URI could not be acquired: 
Elapsed time: 0:00:01
1
1 problemResource errors in /redfish/v1/Systems
Counter({'problemResource': 1})
Validation has failed: 1 problems found
```

And finally the results with the `--ca_bundle` option (works as expected because the server cert is included in the ca_bundle directory):

```
$ python3 RedfishServiceValidator.py -i idrac --authtype Basic -u <user> -p <password> --ca_bundle /tmp/ca_certs --payload Single /redfish/v1/Systems

ConfigURI: https://idrac
System Info: No desc
authtype: Basic,  certificatebundle: /tmp/ca_certs,  certificatecheck: True,  config: None,  httpproxy: None,  httpsproxy: None,  
linklimit: {},  localonlymode: False,  logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  payloadfilepath: /redfish/v1/Systems,  payloadmode: Single,  
sample: 0,  schemasuffix: _v1.xml,  servicemode: False,  timeout: 30,  token: None,  username: root,  
usessl: True,  v: False,  
Start time: 12/15/17 - 15:16:19

*** Target, /redfish/v1/Systems
/usr/local/lib/python3.5/site-packages/urllib3/connection.py:344: SubjectAltNameWarning: Certificate for idrac has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

[...]

#ComputerSystemCollection.ComputerSystemCollection:Members
	value: [OrderedDict([('@odata.id', '/redfish/v1/Systems/System.Embedded.1')])] <class 'list'>
	has Type: Collection(ComputerSystem.ComputerSystem) entity
	is Optional
	is Collection
/usr/local/lib/python3.5/site-packages/urllib3/connection.py:344: SubjectAltNameWarning: Certificate for idrac has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
	Success
Resource.v1_0_0.ResourceCollection:Description
	value: Collection of Computer Systems <class 'str'>
	has Type: Resource.Description Edm.String
	is Optional
	Success
Resource.v1_0_0.ResourceCollection:Name
	value: Computer System Collection <class 'str'>
	has Type: Resource.Name Edm.String
	is Optional
	Success
Resource.v1_0_0.ResourceCollection:Oem
	value: n/a <class 'str'>
	has Type: Resource.Oem complex
	Oem is skipped
In the resource $metadata, the RedfishExtensions.v1_0_0 namespace must have an alias of 'Redfish'. The alias is missing. This may cause properties of the form [PropertyName]@Redfish.TermName to be unrecognized.
Target, ComputerSystemCollection, ComputerSystemCollection
@odata.context                                          PASS
@odata.id                                               PASS
@odata.type                                             PASS
Description                                             PASS
Members                                                  ...
Members@odata.count                                     PASS
Name                                                    PASS
Members#0                                               PASS
Oem                                                  skipOEM
#ComputerSystemCollection.ComputerSystemCollection, Counter({'pass': 3, 'skipOem': 1, 'passGet': 1})
Elapsed time: 0:00:20
1
Counter({'pass': 3, 'skipOem': 1, 'passGet': 1})
Validation has succeeded.
```

Note that the last case above does get a `SubjectAltNameWarning`. This is expected due to the fact that the self-signed cert was generated without the Subject Alternative Name field.

I will also add an additional comment here summarizing how I created the ca_certs bundle directory I used for this test.

**Comment by billdodd** [comment] 2017-12-15 22:41
Steps to create a certificate bundle directory that works with the verify=CA_BUNDLE option in the python `requests` library:

The steps below use a couple of commands from the openssl package. If it's not already installed on your system, go ahead and find and install it.

The steps here also assume you already have a Redfish service up and running that uses a self-signed cert.

**Step 1.** Get the certificate for your service into a PEM format file.

If you were the one that generated your self-signed cert, you may already have this at hand. But if not, you can get it from the running service using openssl. Run this openssl command, substituting the proper IP address and port for your service:

```
$ openssl s_client -connect <IP_ADDRESS>:<PORT> -showcerts
```

This will generate a couple (or a few) screenfuls of output. Scroll back through the output and look for a block of text that begins with "-----BEGIN CERTIFICATE-----" and ends with "-----END CERTIFICATE-----". Copy that text (including the  "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" lines) and paste them into a text file. Name the text file with a '.pem' extension, for example, `myhost.pem`.

**Step 2.** Place the file into a directory you will use for your ca_bundle directory for self-signed certs.

For this example, I'll use a directory called `/tmp/ca_certs` and a PEM file called `myhost.pem` (from Step 1).

```
$ mkdir /tmp/ca_certs
$ cp myhost.pem /tmp/ca_certs/
$ ls /tmp/ca_certs/
myhost.pem
```

**Step 3.** Rehash the ca_certs directory. 

This is the step that makes your ca_certs directory recognized as a CA_BUNDLE directory that can be used by various runtimes to validate server certificates.

```
$ c_rehash /tmp/ca_certs/
Doing /tmp/ca_certs/
$ ls /tmp/ca_certs/
889897a9.0 myhost.pem
```

You'll notice that now an additional file has been added to your `/tmp/ca_certs` directory. The name of the file is a based on a hash of the public cert in the .pem file.

**Step 4.** You _may_ need to perform this step depending on whether the hostname where your service is running matches the `CN` or one of the `Subject Alternative Name` values in your certificate.

Rerun the openssl command from Step 1 that displays the contents of your certificate. Look through the output for the `Subject Alternative Name` values (if present) or the `CN` (Common Name) value. You want to be sure the hostname you use to access the service matches one of those names.

For example, let's assume your certificate has a `CN` value of `CN=idrac`. Example:

```
$ openssl s_client -connect <IP_ADDRESS>:<PORT> -showcerts
CONNECTED(00000003)
depth=0 C = US, ST = New York, L = Metropolis, O = Acme Inc., OU = Remote Access Group, CN = idrac, emailAddress = info@example.com
...
```

You would want to be sure you specify a hostname of `idrac` when accessing the service. If that is already the correct hostname for your service, you don't need to perform this step. But if not, you may need to create an entry in your local /etc/hosts file (or equivalent) to map the IP address of your service to that hostname.

So, if the CN looks like 'CN=idrac' and the IP address of your service is 127.0.0.1, add an entry like this to your /etc/hosts: 

```
127.0.0.1   idrac
```

**Step 5.** Use the new ca_certs directory

You should now be able to use the new ca_certs dir you created in a python program using the `requests` library like this:

```
r = requests.get('https://idrac/redfish/v1', verify='/tmp/ca_certs')
```

Or with the Redfish-Service-Validator tool like this:

```
$ python3 RedfishServiceValidator.py -i idrac --authtype Basic -u <user> -p <password> --ca_bundle /tmp/ca_certs --payload Single /redfish/v1/Systems
```

**Comment by mraineri** [comment] 2018-01-04 22:55
Let's migrate this info into the READEME (or another .md file as a guide)

**Closed** 2018-01-11 22:33 UTC
