### ISSUE TITLE
Link to NetworkAdapter/NetworkAdapters check failing

### ISSUE THREAD

**Issue by DileepEx** [DMTF/Redfish-Service-Validator#267] opened 2018-09-04 15:33 UTC
Error:
Links.NetworkAdapter Link: /redfish/v1/Chassis/CARD_001/NetworkAdapters link to: NetworkAdapter Yes FAIL 
ERROR - Links.NetworkAdapter: Could not get schema file for Entity check
WARNING - No such reference NetworkAdapterCollection in local./SchemaFiles/metadata/NetworkInterface_v1.xml 

As per the redfish schema, NetworkInterface_v1.xml says NetworkAdpater is of type NetworkAdapter.NetworkAdapter not of type NetworkAdapterCollection as follows:

-<NavigationProperty Name="NetworkAdapter" Type="NetworkAdapter.NetworkAdapter" Nullable="false">

As per Schema:
NetworkAdapter should link to NetworkAdapter.NetworkAdapter
NetworkAdapters should link to NetworkAdpaterCollection.NetworkAdpaterCollection
But one of the check seems to be is incorrect.

**Comment by tomasg2012** [comment] 2018-09-04 15:59
Would you be able to zip and post the associated logs with `--debug_logging`?

**Comment by DileepEx** [comment] 2018-09-07 18:52
[Bug_267_Debuglog.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2362169/Bug_267_Debuglog.zip)

**Comment by DileepEx** [comment] 2018-09-12 00:06
@mudaliarh

**Comment by tomasg2012** [comment] 2018-09-12 00:31
Apologies, I had reviewed this error and it seems that you're linking to a collection of NetworkAdaptors when that particular property is supposed to link to a single NetworkAdaptor.  The error isn't specifically clear, however.

In the HTML report:
Links.NetworkAdapter | Link: /redfish/v1/Chassis/CARD_001/NetworkAdapters | link to: NetworkAdapter | Yes | FAIL

**Comment by mraineri** [comment] 2018-09-13 21:46
So, the root of the issue is the fact that in the resource "NetworkInterface", the property "NetworkAdapter" is supposed to be pointing to a NetworkAdapter resource, but in this implementation it's pointing to a NetworkAdapterCollection resource. The error message does need work to highlight this, but it's certainly an error condition.

**Comment by DileepEx** [comment] 2018-09-20 10:58
Thanks for the support. We fixed the link to point to a NetworkAdapter instance, and the validator approves the same.
@tomasg2012 , @mraineri, 
Should I close the bug or keep the Bug open to fix the error message?

**Comment by mraineri** [comment] 2018-09-20 11:46
Please keep it open; we'd like to make the error message more useful in the future.

**Comment by mraineri** [comment] 2018-10-11 21:41
Closing; fixed in latest PR

**Closed by mraineri** 2018-10-11 21:41 UTC
