### ISSUE TITLE
Allow Extra Headers - Feature removed?

### ISSUE THREAD

**Issue by nandagopal-nv** [DMTF/Redfish-Service-Validator#452] opened 2022-01-24 06:33 UTC
I see there was a provision to include custom JSON headers #135 but can't seem to find this feature in the latest version (2.0.9). Has this feature been moved to some other section? 
For context, trying to add the header `Accept-Encoding` with value `gzip, deflate, br`. I am able to hardcode this into `traverse.py` but I can't seem to find a provision in the config file to add these.
![image](https://user-images.githubusercontent.com/33775527/150733386-03975eb9-b5d5-4415-95ca-85709a39387b.png)

**Comment by tomasg2012** [comment] 2022-01-24 23:44
It used to be an option but was removed to streamline the command line operation by version 2.

**Comment by nandagopal-nv** [comment] 2022-01-25 10:45
Is there a work-around? Is there another way to provide custom headers without hardcoding them in as seen in the screenshot above?

**Comment by mraineri** [comment] 2022-01-26 21:04
The functionality was removed intentionally because upon further review, this goes outside the requirements of an implementation and the usage of this tool. Ultimately content encoding handling is done by the python-redfish-library, and the JSON response is cracked open and validated.

Is there a particular reason why you want to force responses to be encoded in a particular manner? At the end of the day, the scope of the service validator is verifying the resources conform against schema definitions; whether they come back as gzip encoded or no encoding is not relevant.

**Comment by raghul1998** [comment] 2022-01-27 06:07
@mraineri @jautor 
This is related to the issue - [https://github.com/DMTF/Redfish-Mockup-Creator/issues/58](https://github.com/DMTF/Redfish-Mockup-Creator/issues/58) and you have fixed it in the mock up tool. PR - [https://github.com/DMTF/Redfish-Mockup-Creator/pull/62](https://github.com/DMTF/Redfish-Mockup-Creator/pull/62).

Will the same change go into the Service Validator tool as well?

I spoke to Jeff Autor on this issue as well and here is his response.

> Because when we’ve run it in the past during plugfests (last one was probably a year ago for this tool?), this didn’t come up.  There was quite a bit of refactoring over the last year, and so very possible the same issue that occurred in the Mockup Creator showed up here.  A quick search through the code doesn’t show any handling of the accept-encoding header at all – so it’s likely being handled by libraries now. Open an issue on the Validator, and point to the closed issue on the Mockup Creator:  https://github.com/DMTF/Redfish-Mockup-Creator/issues/58

**Comment by mraineri** [comment] 2022-01-28 02:09
Okay, we can take a look at addressing the issue in that manner. Good catch!

It may be worth checking the version of the python-redfish-library you're using; version 3.1.0 replaces a lot of internal functionality to leverage the requests module (including some of the encoding handling). I'll do some testing on my end too since I have access to systems that prompted the change for the mockup creator.

**Comment by mraineri** [comment] 2022-01-31 14:48
At least on the system I have available, running 3.0.3 of the python-redfish-library reproduces the issue, and upgrading to newer versions based on the requests module fixes it.

However, since we can't guarantee everyone will have their modules updated completely, I'll go ahead and add the same Accept-Encoding change we did in the mockup creator.

**Comment by nandagopal-nv** [comment] 2022-02-02 08:44
@mraineri , I tested with the "accept-encoding" branch and the fix you made seems to resolve the issue. This was the same fix that I had tried earlier (in the screenshot attached above). 

> _However, since we can't guarantee everyone will have their modules updated completely_, I'll go ahead and add the same Accept-Encoding change we did in the mockup creator.

Yes, this was our main concern. Can you go ahead and merge this change into the master branch as well?

Thanks!

**Comment by mraineri** [comment] 2022-02-02 15:10
Sure, it'll be reviewed by the group and merged during the usual tool review cadence; it'll likely get into master at the end of the week.

**Closed** 2022-02-04 20:21 UTC
