### ISSUE TITLE
$metadata and Redfish.AllowableValues not defined issue

### ISSUE THREAD

**Issue by Andrew1013** [DMTF/Redfish-Service-Validator#242] opened 2018-06-25 13:53 UTC
I got some problems need you help, could someone help to give me advices?

1. The report appeared the message *"ERROR - Unable to retrieve $metadata resource at /redfish/v1/$metadata"*, I tried to use curl tool to verify it but it seemed to work properly. (curl_get_$metadata.log of attached file)

2.  The report appeared the message *"ERROR - IndicatorLED@Redfish.AllowableValues not defined in schema Chassis.v1_4_0 (check version, spelling and casing)"*, the Redfish codebase  follows DSP0266 1.1.0 Specification and Redfish Schema 2016.3, I tried to use Schema 2018.1 to verify it but still got some issue. (Image 2.jpg of attached file)

Attached file.
[logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2133371/logs.zip)

**Comment by billdodd** [comment] 2018-06-25 16:04
For (1), the issue is that the response for the $metadata should be specifying a Content-Type header of `application/json`, but it is using `text/html` (as seen in your `curl_get_\$metadata.log` file).

Not sure about (2). It is possible it is a side-effect of (1) since the tool didn't process the set of schemas specified in the $metadata.

**Comment by mraineri** [comment] 2018-06-25 16:40
Correction; it should be `application/xml` (not json). But `text/html` is definitely wrong.

**Comment by mraineri** [comment] 2018-06-25 16:41
Maybe the tool needs to be more forgiving about HTTP headers; that sort of testing should be done by the Service Conformance Check tool.

**Comment by billdodd** [comment] 2018-06-25 16:51
Oops. Thanks for the correction, Mike. I corrected it in my original comment above.

Agree that it is reasonable to make the tool more forgiving of this type of header issue. (This is checked by the conformance check tool.)

**Comment by tomasg2012** [comment] 2018-06-26 06:41
Sorry, this was mentioned in another adjacent issue.  The $metadata message is a recent oversight with the latest PR, and has been fixed in a branch.  Addtionally, there is another issue with $metadata which refuses to print out what Namespaces are missing in the text log and potentially the HTML log as well, which needs to be reviewed a bit more in the branch.  So there is no problem with your $metadata being acquired, that is a tool problem.

Would you be able to post the contents of your $metadata for your latter issue?

**Comment by Andrew1013** [comment] 2018-06-26 07:47
update $metadata file.
[$metadata.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2136049/metadata.zip)

**Comment by tomasg2012** [comment] 2018-06-26 09:20
It appears the tool wasn't vetting the annotation names in the payload properly, and was treating them as additional and overwriting the tests it had done.  The PR #244 should now fix that.

**Comment by tomasg2012** [comment] 2018-07-01 02:00
Should be fixed with latest PR

**Comment by tomasg2012** [comment] 2018-08-09 11:46
Closed finished issue.

**Closed by tomasg2012** 2018-08-09 11:46 UTC
