### ISSUE TITLE
Schema missing from $metadata error no longer appear in error summary

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#151] opened 2018-02-02 00:46 UTC
With the clean up of the resource-level reporting and summary, errors caused by $metadata are still flagged as errors, but there is no indication of failure unless the resource details are expanded.

**Comment by billdodd** [comment] 2018-02-08 19:11
Same root cause and fix as issue #154. Fixed in PR #164.

**Closed** 2018-02-08 22:38 UTC
Labels: enhancement
