### ISSUE TITLE
Links in LogEntryCollection are not followed and checked

### ISSUE THREAD

**Issue by jiaqingz-intel** [DMTF/Redfish-Service-Validator#519] opened 2022-10-17 06:09 UTC
Version: 2.2.1

Validator only checks the `LogEntry` in the response payload of `LogEntryCollection`, the `LogEntry` resourced linked at `@odata.id` is not checked. (Response time is 0 and HTTP status is -1)

![image](https://user-images.githubusercontent.com/89004540/196100890-ab3252bf-7b7e-49b5-b444-4df20102c226.png)

When the `LogEntry` resources at `@odata.id` is incorrect, as validator skips them, no error reported.

![image](https://user-images.githubusercontent.com/89004540/196100719-bb69a1f7-cf77-4101-b3bf-de106ee59553.png)

**Comment by jiaqingz-intel** [comment] 2022-10-18 01:55
> Edit: Oh, nevermind. It is likely because the validator is not checking the DIRECT call to that odata.id, it is checking it from within the collection without GETting it from the service from it's URI twice (Note the 0ms response time).

Oh I see, in other LogEntryCollection, it also does not follow the link.

![image](https://user-images.githubusercontent.com/89004540/196317110-ef4a35dc-65db-446b-b2b3-5830942499fb.png)

> I believe there's code in place for some URIs checked but not unique URIs like this. This is an assumption from the tool, and needs to be reported correctly.

I think only not following the links with `#` is the correct behavior, like this

![image](https://user-images.githubusercontent.com/89004540/196317052-fea3df8a-0ffe-45b3-bc04-31c942cfacbf.png)

Anyway I'm going to update the issue.

**Comment by blakehilliard** [comment] 2023-04-07 21:37
I am also seeing this error. In `validateURITree()` of validateResource.py, it goes down the path `if link.Type is not None and link.Type.AutoExpand` because `AutoExpand` is set to true for LogEntry in the tool. And so it assumes the the collection it already got was auto-expanded, even though it did not request it to be expanded. So then it processes just the odata.id object in Members as if it were the full LogEntry resource and complains that it is missing every field except odata.id.

**Comment by mraineri** [comment] 2023-04-08 13:59
The collection is supposed to be expanded even if not requested; if LogEntryCollection does not show the contents of the LogEntry resources in the Members array, it's nonconformant.

**Comment by mraineri** [comment] 2023-04-08 16:50
@blakehilliard to be clear, are you saying the collection is auto expanded and the case is it's treating it like it's not? Do you have a sample of what you're running exactly from the command line?

**Comment by mraineri** [comment] 2023-04-11 16:10
To date, we only have that requirement on the LogEntryCollection (with the OData.AutoExpand term specified on the Members NavigationProperty). In theory it could be applied elsewhere, but there hasn't been a need to force expansion like with logs. The service validator dynamically looks for the OData.AutoExpand term to determine whether or not it should expect the expansion in the response (and validates accordingly).

**Comment by mraineri** [comment] 2024-06-28 19:41
Closing; tool is functioning as designed and leveraging auto-expansion as the schema dictates.

**Closed by mraineri** 2024-06-28 19:41 UTC
Labels: cleanup
