### ISSUE TITLE
Resource Type versions

### ISSUE THREAD

**Issue by lindappwu** [DMTF/Redfish-Service-Validator#172] opened 2018-02-22 00:19 UTC
Why do we use newer versions for validating reference members?
Example as below:

**/redfish/v1/Chassis/1/Thermal (response time: 1.260085s) (Thermal v1_0_0)**
Schema File: http://xx.xx.xx.xx/schemas/v1/Thermal_v1.xml
Resource Type: Thermal v1_0_0

**/redfish/v1/Chassis/1/Thermal#/Temperatures/0 (response time: 0s) (Temperature v1_3_0)**
Schema File: http://xx.xx.xx.xx/schemas/v1/Thermal_v1.xml
Resource Type: Temperature v1_3_0

**/redfish/v1/Chassis/1/Thermal#/Fans/0 (response time: 0s) (Fan v1_3_0)**
Schema File: http://xx.xx.xx.xx/schemas/v1/Thermal_v1.xml
Resource Type: Fan v1_3_0

**Comment by billdodd** [comment] 2018-02-22 21:03
My guess is that this is related to the fix for issue #160 (made via PR #163).

@tomasg2012 - can you comment?

**Comment by tomasg2012** [comment] 2018-02-26 19:37
Since these are entity types, by default the code (given that there ISN'T @odata.type inside a Fan/Temperature) gives them the highest possible type available.  If the implementation requires a specific version number, it needs to specify an @odata.type.  However, if the implementation you're using does have @odata.type, then please let us know.

In any case, the behavior may be changed to match with the owner's type version, but I don't know if that's correct.  Regardless, it is incorrect (or at least, discouraged) not to have @odata.type in an Entity.

**Comment by lindappwu** [comment] 2018-02-26 22:59
If that is the case, there's backward compatibility issue.
For example, we used FanName at the initial release(Thermal.v_1_0_0), and then changed to Name. 
The service would be flagged errors because it verified against Themal.v_1_1_0.

----
ERROR - FanName: The given property is deprecated: This property has been Deprecated in favor of Thermal.v1_1_0.Thermal.Fan.Name

**Comment by tomasg2012** [comment] 2018-02-27 01:03
Oh, that is interesting.  For one, I don't think the deprecation is should be an error, it's only supposed to report it as WARN.  I think the HTML reporting errors vs warnings will have to be revamped a bit.  I think regardless of whether or not something is deprecated should be still be reported.

However, the fact that it automatically checks the highest type is a bother, but I don't know for sure if it's been established that an embedded Entity without an @odata.type should be reported as the highest type regardless of the parent. @mraineri, do you know of any rules on this?

If you could, as well, post a snippet of a Temperature or Fan object in your system as example?

**Comment by lindappwu** [comment] 2018-02-27 18:39
I agree deprecation to report as warning, not an error. 

Also, I thought the type version of an embedded entity is based on parent's version by default. 
We should have clear statement on the specification for this.

Here is a snippet of the response.
{
	"@odata.context": "/redfish/v1/$metadata#Thermal.Thermal",
	"@odata.type": "#Thermal.v1_0_0.Thermal",
	"@odata.id": "/redfish/v1/Chassis/1/Thermal",
	"Id": "Thermal",
	"Name": "Thermal",
	"Temperatures":[
		...
	],
	"Fans":[
		{
			"@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/0",
			"MemberId": "0",
			"FanName": "FAN1",
			"PhysicalContext": "Backplane",
			"Status":{"State": "Absent"},
			"ReadingUnits": "RPM",
			"Reading": 0,
			"UpperThresholdNonCritical": 0,
			"UpperThresholdCritical": 0,
			"UpperThresholdFatal": 0,
			"LowerThresholdNonCritical": 0,
			"LowerThresholdCritical": 0,
			"LowerThresholdFatal": 0,
			"MinReadingRange": 0,
			"MaxReadingRange": 0,
			"RelatedItem":[{"@odata.id": "/redfish/v1/Systems/1" }, {"@odata.id": "/redfish/v1/Chassis/1"…]
		},
		...
	]
}

**Comment by mraineri** [comment] 2018-02-28 16:20
So, the problem is from a generic OData perspective, the type of the object could be any type of Temperature definition (since each type builds on previous definitions). When `@odata.type` is not provided, it assumes the "newest" version of the type. This is especially critical to do when referencing external schema files (like Chassis referencing the Location definition in Resource). However, in the context of using definitions in the local schema file, we probably do not need to do that (but the effect should be benign since newer versions are supposed to be backwards compatible). With that said, I suppose it could be possible to detect when the definition is "local", and then use the equivalent version for consistency (such as if the resource is of type Thermal.v1_2_0.Thermal, then use the Thermal.v1_2_0.Temperature definition instead of searching for the newest one).

**Comment by billdodd** [comment] 2018-04-19 18:28
The current code is reporting deprecated properties as warnings, not errors. (See issue #178, fixed via PR #184.) 

@mraineri - regarding the possibility of changing the behavior when the definition is "local": From your comment, it doesn't sound like this change is required. Do we want to make that change?

**Comment by mraineri** [comment] 2018-04-19 19:29
I think we still want to make some sort of change here. For example, let's say a service's Thermal payload contains `@odata.type` set to "#Thermal.v1_2_0.Thermal". If the Temperature instances contains properties that are defined in "Thermal.v1_5_0.Temperature", that would be an error.

**Closed as completed** 2018-08-23 21:22 UTC

**Comment by tomasg2012** [comment] 2018-08-23 21:37
@lindappwu Is the latest master branch satisfactory for the typing issue?

**Comment by lindappwu** [comment] 2018-08-23 22:43
@tomasg2012  yes, thanks for the fix!
